# This file was generated by GoReleaser. DO NOT EDIT.
cask "capstan" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d3c05910b53e530e18b6b5f19f76c541498e95a48135c115fa02dee895c6076a"
      url "https://github.com/artisan-build/capstan-cli/releases/download/v#{version}/capstan_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c067c5d694e723127d70d89d327bf562adc43a5a3d67541e70c90cdd358640f0"
      url "https://github.com/artisan-build/capstan-cli/releases/download/v#{version}/capstan_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "97056de495dd7df8dd55a312d01c33a898c385fb789a68ba8ebfe627b76c18ed"
      url "https://github.com/artisan-build/capstan-cli/releases/download/v#{version}/capstan_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f96916ce03549000c479e2d99310f1612241610227794f694be373e0fc3a66f8"
      url "https://github.com/artisan-build/capstan-cli/releases/download/v#{version}/capstan_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capstan"
  desc "Command-line client for the Capstan ecosystem server."
  homepage "https://github.com/artisan-build/capstan-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capstan"

  # No zap stanza required

end
