# This file was generated by GoReleaser. DO NOT EDIT.
cask "hitch" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "50e075e7ebecb8fcd8b81ea9ad447fdf36561f15104a6f4e17b818d6c37bc961"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "92cbe9c25b0a430049c33fd64b60186ee81c953d93f0411ae3af0cdab61794aa"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26f11f7c4f1f9896ea10d021d53112b679bd2039ce8080aa8b4a85b82713b660"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "96274cc84af21c68bf6363ea15c346e7aa43b8e73749a0b153d837436bb79ee8"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_arm64.tar.gz"
    end
  end

  name "hitch"
  desc "Install MCP servers into coding agents safely"
  homepage "https://github.com/artisan-build/hitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hitch"

  # No zap stanza required

end
