# This file was generated by GoReleaser. DO NOT EDIT.
cask "hitch" do
  version "0.0.7"

  on_macos do
    on_intel do
      sha256 "daf159e6a9c9412be7a2545c54330494fc5eadcda586a4e8b24be0d8c04eba53"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c80bcde382249f81571898a09cb8b021e905f38222f041f7f80f8cdd3f91b44a"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6fbb0072d91cc3f09f6fe87481dfa8195883ce0f21a617351dec48afad9cb0f9"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "acdd1ad93e42c9c8316e8206a948a9e29b54c1005ca7d60a0a9e59169949d6a7"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_arm64.tar.gz"
    end
  end

  name "hitch"
  desc "Install MCP servers into coding agents safely"
  homepage "https://github.com/artisan-build/hitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hitch"

  # No zap stanza required

end
