# This file was generated by GoReleaser. DO NOT EDIT.
cask "hitch" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "3ffe0f5faf730a4f62aa9b4a776f1bc830a15ac9318304035def9e023937976d"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b58ca2baf64f9f9aebeb78cd2c9574d5e4a825a62c5c5511c148112f087ac35f"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8c15b1e5b0647699b0c8d9ed92080c0c6a47246813515b8e9a08ffb979095d3d"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d48a768254f2c9a92fd029a770a5f96af772c8e5ae19daa3c7e1c8cb10375ed9"
      url "https://github.com/artisan-build/hitch/releases/download/v#{version}/hitch_linux_arm64.tar.gz"
    end
  end

  name "hitch"
  desc "Install MCP servers into coding agents safely"
  homepage "https://github.com/artisan-build/hitch"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hitch"

  # No zap stanza required

end
