# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by the ballast-cli release pipeline (scripts/generate_formula.py)
# on each tagged release. Do not edit by hand — changes will be overwritten.
class Ballast < Formula
  desc "Local-first durability-scoring CLI that wraps the settle engine"
  homepage "https://github.com/artisan-build/ballast-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ballast.now/cli/0.2.0/ballast-macos-arm64"
      sha256 "a90ce151d51e01dd38f10936592339584dbee01608a9668bdad5bd345996d04b"
    else
      url "https://ballast.now/cli/0.2.0/ballast-macos-x86_64"
      sha256 "958ee1c0c2e55b5bfc3c33a6146ad7a49e12f7df2f25c4c7478029c7d0fc15c3"
    end
  end

  def install
    # The download is the bare per-arch binary; install it as `ballast`.
    bin.install Dir["ballast-macos-*"].first => "ballast"
  end

  test do
    assert_match "ballast", shell_output("#{bin}/ballast --version")
  end
end
