# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by the ballast-cli release pipeline (scripts/generate_formula.py)
# on each tagged release. Do not edit by hand — changes will be overwritten.
class Ballast < Formula
  desc "Local-first durability-scoring CLI that wraps the settle engine"
  homepage "https://github.com/artisan-build/ballast-cli"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ballast.now/cli/0.5.0/ballast-macos-arm64"
      sha256 "11e8eaff344232dba03e04beebfcf80d052f15f0b00ab93d46e9b367b6780a6a"
    else
      url "https://ballast.now/cli/0.5.0/ballast-macos-x86_64"
      sha256 "7828e74727f66b5e3b745bfd010c4fcc41408a1a286bd7b7331b54a8b6bf597c"
    end
  end

  def install
    # The download is the bare per-arch binary; install it as `ballast`.
    bin.install Dir["ballast-macos-*"].first => "ballast"
  end

  test do
    assert_match "ballast", shell_output("#{bin}/ballast --version")
  end
end
