# typed: false
# frozen_string_literal: true

# AUTO-GENERATED by the ballast-cli release pipeline (scripts/generate_formula.py)
# on each tagged release. Do not edit by hand — changes will be overwritten.
class Ballast < Formula
  desc "Local-first durability-scoring CLI that wraps the settle engine"
  homepage "https://github.com/artisan-build/ballast-cli"
  version "0.9.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://ballast.now/cli/0.9.1/ballast-macos-arm64"
      sha256 "ca1de4c29b135c0b6ab87db8725822e586865ab15a840891b1794cb4c3ea1a31"
    else
      url "https://ballast.now/cli/0.9.1/ballast-macos-x86_64"
      sha256 "569c7cf1ff706f81b0e80d9c26f94703f50730694bcaaa741820973fd4de7ca2"
    end
  end

  def install
    # The download is the bare per-arch binary; install it as `ballast`.
    bin.install Dir["ballast-macos-*"].first => "ballast"
  end

  test do
    assert_match "ballast", shell_output("#{bin}/ballast --version")
  end
end
